// src/protocol.rs

/// Autogenerated Wayland client bindings for the River window management protocol.
///
/// This module uses `wayland_scanner` to parse the `river-window-management-v1.xml`
/// protocol specification and generate the corresponding Rust interfaces and client code.
pub mod river_window_manager {
    use wayland_client;
    use wayland_client::protocol::*;

    pub mod __interfaces {
        use wayland_client::protocol::__interfaces::*;
        wayland_scanner::generate_interfaces!("protocols/river-window-management-v1.xml");
    }
    use self::__interfaces::*;

    wayland_scanner::generate_client_code!("protocols/river-window-management-v1.xml");
}

/// Autogenerated Wayland client bindings for the River XKB bindings protocol.
///
/// This module uses `wayland_scanner` to parse the `river-xkb-bindings-v1.xml`
/// protocol specification and generate the corresponding Rust interfaces and client code.
/// It relies on the seat interface defined in the `river_window_manager` module.
pub mod river_xkb_bindings {
    use super::river_window_manager::river_seat_v1;
    use wayland_client;

    pub mod __interfaces {
        use super::super::river_window_manager::__interfaces::*;

        wayland_scanner::generate_interfaces!("protocols/river-xkb-bindings-v1.xml");
    }
    use self::__interfaces::*;

    wayland_scanner::generate_client_code!("protocols/river-xkb-bindings-v1.xml");
}

pub mod river_layer_shell {
    use super::river_window_manager::{river_output_v1, river_seat_v1};
    use wayland_client;

    pub mod __interfaces {
        use super::super::river_window_manager::__interfaces::*;

        wayland_scanner::generate_interfaces!("protocols/river-layer-shell-v1.xml");
    }
    use self::__interfaces::*;

    wayland_scanner::generate_client_code!("protocols/river-layer-shell-v1.xml");
}
